"use strict";
let favouritePlaces = ["Dubai", "Kashimr", "Qatar", "Philippines", "London"];
console.log(favouritePlaces);
console.log(["Dubai", "Kashimr", "Qatar", "Philippines", "London"].sort());
console.log(favouritePlaces);
console.log(["Dubai", "Kashimr", "Qatar", "Philippines", "London"].reverse());
console.log(favouritePlaces);
favouritePlaces.reverse();
console.log(favouritePlaces);
favouritePlaces.reverse();
console.log(favouritePlaces);
favouritePlaces.sort();
console.log(favouritePlaces);
favouritePlaces.reverse();
console.log(favouritePlaces);
