"use strict";
let guests = ["Ahad", "Sarim", "Ayan", "Suffiyan", "Naveed", "Ali", "Jawad"];
let deletedGuest1 = guests.pop();
console.log("We are sorry Dear", deletedGuest1, "We can not invited you at dinner");
let deletedGuest2 = guests.pop();
console.log("We are sorry Dear", deletedGuest2, "We can not invited you at dinner");
let deletedGuest3 = guests.pop();
console.log("We are sorry Dear", deletedGuest3, "We can not invited you at dinner");
let deletedGuest4 = guests.pop();
console.log("We are sorry Dear", deletedGuest4, "We can not invited you at dinner");
let deletedGuest5 = guests.pop();
console.log("We are sorry Dear", deletedGuest5, "We can not invited you at dinner");
console.log(guests);
guests.forEach((val) => {
    console.log("Dear", val, "You are invited at dinner");
});
let deletedGuest6 = guests.pop();
console.log("We are sorry Dear", deletedGuest6, "We can not invited you at dinner");
let deletedGuest7 = guests.pop();
console.log("We are sorry Dear", deletedGuest7, "We can not invited you at dinner");
console.log(guests);
